"""Y30 cognitive-boundary substrate for Chronos.

Y30 records appearance, dependence, construction, projection, seed-trace, and
unknown-boundary structures. It is no-LLM, stdlib-only, and does not certify
metaphysical or physical truth.
"""

from .core import (
    BANNED_SUBSTRINGS,
    TOY_BOUNDARY,
    UNKNOWN_TYPES,
    PROJECTION_TYPES,
    AppearanceEvent,
    DependentConditions,
    ObjectConstructionClaim,
    ProjectionClaim,
    SeedTrace,
    SelfGraspingSignal,
    ThreeNatureAnalysis,
    UnknownBoundary,
)
from .bridge import attach_y30_context, claim_from_y30_core_summary
from .physics_bridge import (
    K3_2D_VERDICTS,
    Y30Context,
    attach_y30_context_full,
    explain_k3_2d_verdict,
    k1_causal_overreach_warning,
    k1_causal_unknown_boundary,
    k1_context,
    k2_context,
    k2_universalization_overclaim_warning,
    k3_2d_seed_trace_from_verdict,
    k3_context,
    k3_identity_overreach_warning,
    k3_transport_unknown_boundary,
)
from .realizer import (
    realize_alaya_store,
    realize_appearance,
    realize_consciousness_flow,
    realize_dependent_conditions,
    realize_manas_attachment,
    realize_mano_construction,
    realize_object_construction,
    realize_projection,
    realize_seed_trace,
    realize_self_grasping,
    realize_sense_consciousness,
    realize_three_nature,
    realize_unknown_boundary,
)
from .stack import (
    ALLOWED_LAYER_ACTIONS,
    ATTACHMENT_TYPES,
    LAYERS,
    SENSE_BASES,
    AlayaSeedStore,
    ConsciousnessFlow,
    LayerActivation,
    ManasAttachment,
    ManoConstruction,
    SenseConsciousnessEvent,
)

__all__ = [
    "ALLOWED_LAYER_ACTIONS",
    "AppearanceEvent",
    "AlayaSeedStore",
    "ATTACHMENT_TYPES",
    "BANNED_SUBSTRINGS",
    "ConsciousnessFlow",
    "DependentConditions",
    "K3_2D_VERDICTS",
    "LAYERS",
    "LayerActivation",
    "ManasAttachment",
    "ManoConstruction",
    "ObjectConstructionClaim",
    "PROJECTION_TYPES",
    "ProjectionClaim",
    "SENSE_BASES",
    "SeedTrace",
    "SelfGraspingSignal",
    "SenseConsciousnessEvent",
    "TOY_BOUNDARY",
    "ThreeNatureAnalysis",
    "UNKNOWN_TYPES",
    "UnknownBoundary",
    "Y30Context",
    "attach_y30_context",
    "attach_y30_context_full",
    "claim_from_y30_core_summary",
    "explain_k3_2d_verdict",
    "k1_causal_overreach_warning",
    "k1_causal_unknown_boundary",
    "k1_context",
    "k2_context",
    "k2_universalization_overclaim_warning",
    "k3_2d_seed_trace_from_verdict",
    "k3_context",
    "k3_identity_overreach_warning",
    "k3_transport_unknown_boundary",
    "realize_alaya_store",
    "realize_appearance",
    "realize_consciousness_flow",
    "realize_dependent_conditions",
    "realize_manas_attachment",
    "realize_mano_construction",
    "realize_object_construction",
    "realize_projection",
    "realize_seed_trace",
    "realize_self_grasping",
    "realize_sense_consciousness",
    "realize_three_nature",
    "realize_unknown_boundary",
]
