"""Standard failure-mode names for Chronos claim records."""

from __future__ import annotations

PIPELINE_OK_TRANSPORT_FAIL = "PIPELINE_OK_TRANSPORT_FAIL"
ACTIVE_NO_ADVANTAGE = "ACTIVE_NO_ADVANTAGE"
RANDOM_ALSO_SUCCEEDS = "RANDOM_ALSO_SUCCEEDS"
TRUTH_STABLE_NEURAL_UNLEARNABLE = "TRUTH_STABLE_NEURAL_UNLEARNABLE"
PENDING_GPU_VALIDATION = "PENDING_GPU_VALIDATION"
CONTROL_DEGENERATE = "CONTROL_DEGENERATE"
REGIME_INVALID = "REGIME_INVALID"
MECHANISM_DECAYS = "MECHANISM_DECAYS"
DIAGNOSTICS_INSUFFICIENT = "DIAGNOSTICS_INSUFFICIENT"
PRIOR_NO_EFFECT = "PRIOR_NO_EFFECT"

KNOWN_FAILURE_MODES = frozenset(
    {
        PIPELINE_OK_TRANSPORT_FAIL,
        ACTIVE_NO_ADVANTAGE,
        RANDOM_ALSO_SUCCEEDS,
        TRUTH_STABLE_NEURAL_UNLEARNABLE,
        PENDING_GPU_VALIDATION,
        CONTROL_DEGENERATE,
        REGIME_INVALID,
        MECHANISM_DECAYS,
        DIAGNOSTICS_INSUFFICIENT,
        PRIOR_NO_EFFECT,
    }
)


def is_known_failure_mode(mode: str | None) -> bool:
    return mode is None or mode in KNOWN_FAILURE_MODES


__all__ = [
    "ACTIVE_NO_ADVANTAGE",
    "CONTROL_DEGENERATE",
    "DIAGNOSTICS_INSUFFICIENT",
    "KNOWN_FAILURE_MODES",
    "MECHANISM_DECAYS",
    "PENDING_GPU_VALIDATION",
    "PIPELINE_OK_TRANSPORT_FAIL",
    "PRIOR_NO_EFFECT",
    "RANDOM_ALSO_SUCCEEDS",
    "REGIME_INVALID",
    "TRUTH_STABLE_NEURAL_UNLEARNABLE",
    "is_known_failure_mode",
]
